### ISSUE TITLE
 WebDriverError: unknown error: cannot find Chrome binary

### ISSUE THREAD

**Issue by ReginaUsil** [usil/seleniumjs4all-demo#1]
/**
   *
   * browserDriver.js
   * 
   */
const chrome = require("selenium-webdriver/chrome");
const firefox = require("selenium-webdriver/firefox");
const path = require("path");
const { Builder } = require("selenium-webdriver");
require("dotenv").config();
require("chromedriver");
require("geckodriver");
const packPath = require("package-json-path");

const rootPath = path.dirname(packPath(("")));

const browserOptions = require(path.join(rootPath, "browserOptions.json"));

const browserDriver = {
  /**
   *
   * @returns WebDriver
   * @description Return the driver for chrome
   */
  chrome: async () => {
    let chromeOptions = new chrome.Options();
    let optionsKeys;
    if (browserOptions.options) {
      optionsKeys = Object.keys(browserOptions.options);
    }
    if (optionsKeys?.length > 0) {
      optionsKeys.map(option => {
        try {
          if ( typeof browserOptions.options[option] === "string") {
            chromeOptions = chromeOptions[option](browserOptions.options[option]);
          } else if (Array.isArray(browserOptions.options[option])) {
            chromeOptions = chromeOptions[option](...browserOptions.options[option]);
          }
        } catch (error) {
          console.log("There are error when you try set chrome options, check your browserOptions.json file");
          console.log(error)
        }
      })
    }
    const driver = await new Builder()
      .forBrowser("chrome")
      .setChromeOptions(chromeOptions)
      .build();
    return driver;
  },
  /**
   *
   * @returns WebDriver
   * @description Return the driver for firefox
   */
  firefox: async () => {
    const driver = await new Builder()
      .forBrowser("firefox")
      .setFirefoxOptions(
        new firefox.Options()
          .addArguments(...browserOptions.arguments)
        // .windowSize(screenSize)
      )
      .build();
    return driver;
  },
};

const envBrowser = process.env.BROWSER;

const browser =
  envBrowser && (envBrowser === "chrome" || envBrowser === "firefox")
    ? envBrowser
    : "chrome";

const getBrowserDriver = browserDriver[browser];

module.exports = getBrowserDriver;

**Comment by jrichardsz** [comment]
Hi Regina.  Thanks for using our framework.  For windows, you should use chromiun, not chrome

![image](https://user-images.githubusercontent.com/3322836/233216034-6b87bbef-3816-4b3e-b83e-865cdc80c575.png)

Check this https://github.com/usil/seleniumjs4all-demo#requirements section in the readme

Cheers

**Comment by ReginaUsil** [comment]
Excellent, thanks Richard you for help
